name: Checks

on:
  push:
    branches:
    - master
    - '[0-9]+.[0-9]+'
  pull_request:

permissions: {}

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
        - python-version: "3.14"
          env:
            TOXENV: typing
        - python-version: "3.14"
          env:
            TOXENV: docs
        - python-version: "3.14"
          env:
            TOXENV: twinecheck
        - python-version: "3.14"
          env:
            TOXENV: pylint

    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        persist-credentials: false

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run check
      env: ${{ matrix.env }}
      run: |
        pip install -U pip
        pip install -U tox
        tox

  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        persist-credentials: false
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
